In [47]:
import numpy as np
import matplotlib.pyplot as plt

import matplotlib.style
import matplotlib as mpl
import matplotlib.colors as colors
import matplotlib.cm as cmx
mpl.style.use('classic')

from astropy.table import Table
from astropy import units as u
from astropy.constants import G

import mesa_helper as mh
import os
import shutil

%matplotlib inline

In [50]:
test = np.genfromtxt("./dere+2000_table7_195angstrom_effectiveArea.txt")
print(test)

[[1.75e+02 1.46e-04 6.78e-05 2.85e-04]
 [1.80e+02 1.27e-03 5.85e-04 2.51e-03]
 [1.85e+02 9.69e-03 4.32e-03 1.90e-02]
 [1.90e+02 1.93e-02 8.63e-03 3.84e-02]
 [1.95e+02 1.25e-02 5.38e-03 2.46e-02]
 [2.00e+02 2.54e-03 1.08e-03 5.13e-03]
 [2.05e+02 9.48e-04 3.89e-04 1.95e-03]
 [2.10e+02 4.60e-04 1.81e-04 9.52e-04]
 [2.15e+02 2.39e-04 9.27e-05 5.17e-04]]


In [57]:
col0 = np.genfromtxt("./col0_temp.txt")
col1 = np.genfromtxt("./col1_temp.txt")
col2 = np.genfromtxt("./col2_temp.txt")
col3 = np.genfromtxt("./col3_temp.txt")

In [58]:
print(col1)

[2.30e-11 5.72e-11 1.40e-10 3.08e-10 2.99e-09 1.30e-05 1.18e-05 1.14e-05
 1.09e-05 1.16e-05 1.20e-05 1.30e-05 1.47e-05 1.53e-05 1.80e-05 1.97e-05
 2.08e-05 2.46e-05 2.74e-05 2.89e-05 3.41e-05 4.30e-05 5.37e-05 7.11e-05
 1.05e-04 1.64e-04 2.32e-04 3.29e-04 5.14e-04 8.54e-04 1.38e-03 1.52e-03
 1.12e-03 6.10e-04 2.84e-04 1.09e-04]


In [59]:
all = np.vstack((col0,col1,col2,col3)).T
print(np.shape(all))

(36, 4)


In [60]:
header="wavelength effectivearea_Al+1[cm^2] effectivearea_Al+2[cm^2] effectivearea_clear[cm^2]"

In [61]:
np.savetxt("./dere+2000_table9_304angstrom_effectiveArea.txt",all,header=header)